export const appColors = {
  core: {
    primaryA: "black",
    primaryB: "white",
    accent: "#FCEF0A",
    negative: "#DE1135",
    warning: "#F6BC2F",
    positive: "#0E8345",
  },
  semantic: {
    background: {
      backgroundPrimary: "#FFFFFF",
      backgroundSecondary: "#F3F3F3",
      backgroundTertionary: "#E8E8E8",
      backgroundInversePrimary: "#000000",
      backgroundInverseSecondary: "#282828",
    },
    content: {
      contentPrimary: "#000000",
      contentSecondary: "#4B4B4B",
      contentTertionary: "#5E5E5E",
      contentInversePrimary: "#FFFFFF",
      contentInverseSecondary: "#DDDDDD",
      contentInverseTertionary: "#A6A6A6",
    },
    border: {
      borderOpacue: "#E8E8E8",
      borderTransparent: "rgba(0,0,0,0.08)",
      borderSelected: "#000000",
      borderInverseOpacue: "#4B4B4B",
      borderInverseTransparent: "#5C5C5C",
      borderInverseSelected: "#FFFFFF",
    },
  },
  semanticExtensions: {
    background: {
      backgroundStateDisabled: "#F3F3F3",
      backgroundOverlayArt: "rgba(0,0,0,0)",
      backgroundOverlayDark: "rgba(0,0,0,0.5)",
      backgroundOverlayElevation: "rgba(0,0,0,0)",
      backgroundAccent: "#FCEF0A",
      backgroundNegative: "#DE1135",
      backgroundWarning: "#F6BC2F",
      backgroundPositive: "#0E8345",
      backgroundLightAccent: "#FFFEE5",
      backgroundLightNegative: "#FFF0EE",
      backgroundLightWarning: "#FDF2DC",
      backgroundLightPositive: "#EAF6ED",
      backgroundAlwaysLight: "#FFFFFF",
      backgroundAlwaysDark: "#000000",
    },
    content: {
      contentStateDisabled: "#A6A6A6",
      contentOnColor: "#FFFFFF",
      contentOnColorInverse: "#000000",
      contentAccent: "#FCEF0A",
      contentNegative: "#DE1135",
      contentWarning: "#9F6402",
      contentPositive: "#0E8345",
    },
    border: {
      borderStateDisabled: "#F3F3F3",
      borderAccent: "#FCEF0A",
      borderNegative: "#DE1135",
      borderWarning: "#9F6402",
      borderPositive: "#0E8345",
      borderAccentLight: "#FFFEE5",
    },
  },
};
