export const FORM_ERRORS = {
  invalidEmail: `Email is invalid.`,
  requiredEmail: `Email is required`,
  requiredPassword: `Password is required`,
  passwordLength: `Password must contain 8 characters`,
  confirmPassword: `Confirm password should match with password`,
  requiredConfirmPassword: `Confirm Password is required`,
  requiredOTP: `OTP is required`,
  otpLength: `OTP must contain 4 digits`,
  requiredSubject: `Subject is required`,
  requiredMessage: `Message is required`,
  invalidName: `Name is required`,
  invalidPhone: `Phone is required`,
  requiredRole: `Role is required`,
  requiredStatus: `Status is required`,
  requireMinspend: `Min Spend is required`,
  invalidMinspend: `Min Spend should be a number`,
  requireDescription: `Description is required`,
};
