import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  mainContainer: {
    borderRadius: theme.units[4],
    boxShadow: "3px 3px 12px 4px rgba(0,0,0,0.08)",
  },
  imgContainer: {
    width: 340,
    height: 200,
    borderTopLeftRadius: theme.units[4],
    borderTopRightRadius: theme.units[4],
    overflow: "hidden",
  },
  fullWidth: {
    width: "100%",
    height: 200,
    borderTopLeftRadius: theme.units[4],
    borderTopRightRadius: theme.units[4],
    overflow: "hidden",
  },
  fullWidthImageStyle: {
    width: "100%",
    height: 200,
  },
  imgStyle: {
    width: 340,
    height: 200,
  },
  fullContentContainer: {
    width: "100%",
    padding: theme.units[3],
    rowGap: theme.units[1],
  },
  contentContainer: {
    width: 340,
    padding: theme.units[3],
    rowGap: theme.units[1],
  },
  contentHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: theme.units[2],
  },
  rightAlignRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: theme.units[1],
  },
  leftAlignRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    columnGap: theme.units[1],
  },
  scoreBadgeContainer: {
    position: "absolute",
    top: theme.units[3],
    left: theme.units[3],
    zIndex: 2,
  },
  scoreBadge: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: theme.units[2],
    paddingHorizontal: theme.units[3],
    paddingVertical: theme.units[2],
    borderRadius: 100,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  iconsContainer: {
    position: "absolute",
    top: theme.units[3],
    right: theme.units[3],
    columnGap: theme.units[3],
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    zIndex: 2,
  },
  blurEcoContainer: {
    height: 42,
    paddingHorizontal: theme.units[3],
    borderRadius: 100,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    columnGap: theme.units[2],
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  fullLinearGrad: {
    width: "100%",
    height: 200,
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 1,
  },
  linearGrad: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 340,
    height: 200,
    zIndex: 1,
  },
}));
