export const envConfig = {
  EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  EXPO_PUBLIC_STRIPE_SECRET_KEY: process.env.EXPO_PUBLIC_STRIPE_SECRET_KEY,
  EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY:
    process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY,
  EXPO_PUBLIC_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_WEB_CLIENT_ID,
  EXPO_PUBLIC_WEB_CLIENT_SECRET: process.env.EXPO_PUBLIC_WEB_CLIENT_SECRET,
  EXPO_PUBLIC_API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  EXPO_PUBLIC_API_KEY: process.env.EXPO_PUBLIC_API_KEY,
  EXPO_PUBLIC_STORAGE_BASE_URL: process.env.EXPO_PUBLIC_STORAGE_BASE_URL,
  EXPO_PUBLIC_GOOGLE_KEY: process.env.EXPO_PUBLIC_GOOGLE_KEY,
  EXPO_PUBLIC_GOOGLE_API_URL: process.env.EXPO_PUBLIC_GOOGLE_API_URL,
  EXPO_PUBLIC_GOOGLE_GEO_API: process.env.EXPO_PUBLIC_GOOGLE_GEO_API,
};
